docs: added coming soon clarification to the landing pages for incomplete classifiers
cdiddy77/react-native-mediapipe pull request #118
Opened 2024-05-31 02:39 UTC by Jazmin915

I added a "coming soon" message to each landing page of a classifier we have not worked on yet. I also linked our discord in the message.

2024-06-01 18:21 UTC, rorleth requested changes
As opposed to adding the very same content in 8 files, I'd suggest you put the "coming soon" text in a single file and include that. See https://docusaurus.io/docs/markdown-features/react#importing-markdown for how to do that. 

Bonus points if you put the discord link into a component as well and then use that in all the places where we point to discord like in the header, so if we ever change the invite, we have a single place to change it in the source (DRY principle - do not repeat yourself) and not risk forgetting one or two.

2024-06-04 01:22 UTC, Jazmin915 commented
Im still going to try and get the discord link to be a component but so far I have the "coming soon message" imported from its own file

2024-06-04 02:20 UTC, rorleth commented on docsite/sidebars.ts
> +  tutorialSidebar: [{type: 'autogenerated', dirName: '.', }],
Superfluous comma - I am kinda surprised this didn't barf when building.

2024-06-04 03:33 UTC, Jazmin915 commented
Removed the Superfluous comma

2024-06-04 03:37 UTC, rorleth approved these changes

2024-06-04 03:42 UTC, merged