app icon for facelandmark
cdiddy77/react-native-mediapipe pull request #124
Opened 2024-06-03 03:09 UTC by sukanvisapearyoo

icon added for both ios and android no changes made to design of the app.

2024-06-04 14:16 UTC, cdiddy77 requested changes
Please get rid of the changes to `Podfile.lock` and, in the `objectdetection.xcodeproj`, the `project.pbxproj` since nothing really changed in those files.

2024-06-05 03:14 UTC, sukanvisapearyoo commented on examples/facelandmarkdetection/ios/Podfile.lock
@cdiddy77 youre talking about this file? you want me to change it back to what it was (red)?

2024-06-06 18:18 UTC, cdiddy77 approved these changes
just remove the changes to objectdetection files and you are good

2024-06-06 18:18 UTC, cdiddy77 commented on examples/objectdetection/ios/Podfile.lock
this should be reverted from the commit

2024-06-06 18:18 UTC, cdiddy77 commented on examples/objectdetection/ios/objectdetection.xcodeproj/project.pbxproj
this should be reverted from the PR

2024-06-09 04:41 UTC, sukanvisapearyoo commented on examples/objectdetection/ios/Podfile.lock
I believe i have reverted it

2024-06-22 02:11 UTC, cdiddy77 approved these changes

2024-06-22 02:11 UTC, merged