docs: added few steps to the getting started documentation for face landmark app #101
cdiddy77/react-native-mediapipe pull request #126
Opened 2024-06-04 03:14 UTC by michellrodriguez08

I added the first few steps for the face landmark app for iOS and Android. I reached a small block but as soon as I get that resolved I will add the rest of the steps, just wanted to practice the adding before it's 'perfect'. I also fixed the android configuration bug that Charles mention in the video with the tags and misspells.

2024-06-04 14:13 UTC, cdiddy77 requested changes
Just a few changes. This will be great!

2024-06-04 14:13 UTC, cdiddy77 commented on docsite/docs/api_pages/face-landmark-detection.md
> +    If correctly you should see a **react-native-mediapipe** dropdown inside **node_modules**
this is not necessary. doing `yarn add` is something that react native developers do every day.

2024-06-04 14:13 UTC, cdiddy77 commented on docsite/docs/api_pages/face-landmark-detection.md
> +```
Move this up to where we do the other `yarn add` stuff

2024-06-05 05:21 UTC, michellrodriguez08 commented
I believe I addressed all the feedback received. I also added the rest of the steps to create the face landmark app. I removed the tabs but in my opinion I feel like it looks a bit crowded but let me know if it makes sense to you or if I should look for a different approach. Thank you!

2024-06-06 18:19 UTC, cdiddy77 approved these changes
ty!

2024-06-06 18:19 UTC, merged