contributing.md
cdiddy77/react-native-mediapipe pull request #55
Opened 2024-04-20 01:56 UTC by sukanvisapearyoo

docs(contributing): Modified the 'Get Started' section by adding iOS and android 'Install dependencies' part

2024-04-20 18:32 UTC, cdiddy77 reviewed
This change isn't necessary

2024-04-20 18:32 UTC, cdiddy77 commented on CONTRIBUTING.md
> +   Java Development Kit - Zulu using Homebrew.
this isn't necessary. These sorts of packages all assume that users have already set up a react native development environment.

2024-04-21 01:37 UTC, rorleth commented
Also note: the "issue" work item complains about another issue.

2024-04-23 17:26 UTC, cdiddy77 requested changes
This change isn't really necessary -- as noted, the inserted lines are not needed. Should we close this PR or were there other changes you wanted to make?

2024-04-23 17:34 UTC, sukanvisapearyoo commented
I will make changes. I got some answers from Robert.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Charles P ***@***.***>
Sent: Tuesday, April 23, 2024 10:26:55 AM
To: cdiddy77/react-native-mediapipe ***@***.***>
Cc: sukanvisapearyoo ***@***.***>; Author ***@***.***>
Subject: Re: [cdiddy77/react-native-mediapipe] contributing.md (PR #55)


@cdiddy77 requested changes on this pull request.

This change isn't really necessary -- as noted, the inserted lines are not needed. Should we close this PR or were there other changes you wanted to make?

—
Reply to this email directly, view it on GitHub<https://github.com/cdiddy77/react-native-mediapipe/pull/55#pullrequestreview-2017861111>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/A326HSIANS4N2HAUWEO77HTY62KV7AVCNFSM6AAAAABGQCORBCVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDAMJXHA3DCMJRGE>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

2024-04-24 01:50 UTC, rorleth commented on CONTRIBUTING.md
> +1. Open the `react-native-mediapipe/examples/ios/MediapipeExample.xcworkspace` file with Xcode
That is still not the correct path - there is a folder called objectdetection under /examples/ and the xcworkspace file is called differently.

2024-04-24 03:53 UTC, rorleth approved these changes

2024-04-24 12:30 UTC, merged