feat: added photo-screen using react-native-image-crop-picker
cdiddy77/react-native-mediapipe pull request #70
Opened 2024-04-30 23:03 UTC by shackerman

This code has some issues at the moment but I'm creating this pull request so it can be monitored and to see if we can hammer out some issues with it. Right now the photo-screen shows up when the app first runs on android and then it doesn't open up again. However there are no big crashes with the app yet - so it's getting there.

2024-05-01 19:41 UTC, cdiddy77 requested changes
Remove the files per comments and then re-request review

2024-05-01 19:41 UTC, cdiddy77 commented on package-lock.json
Get rid of this file. It should never be created. You must have typed `npm install ` at some point.

2024-05-01 19:41 UTC, cdiddy77 commented on package.json
This package should not have any change to the dependencies because it is only the example package that requires RNVI. 

Revert changes to this file

2024-05-01 19:41 UTC, cdiddy77 commented on yarn.lock
Based on the failures in your tests, there is something wrong with these changes. But we never edit this file by hand. Instead, revert changes to `package.json` and re-run `yarn` before updating this PR

2024-05-01 19:41 UTC, cdiddy77 commented on examples/objectdetection/src/Photo.tsx
> +  console.log(image);
assuming that when you run the example app locally, when you select a file, you see output in the metro bundler window to the effect that this line of code executed, then this is good.

2024-05-02 23:18 UTC, shackerman commented on package-lock.json
Deleted this file, I thought I had to since the guide told me to run an npm install.

2024-05-02 23:26 UTC, shackerman commented on package.json
Reverted to version 7418742 fix: android inference with faster yuv->rgb conversion (#51), according to git log

2024-05-02 23:27 UTC, shackerman commented on yarn.lock
i reran yarn and it just said "Done with warnings in 3s 911ms" so I assume that means it's okay?

2024-05-08 00:51 UTC, closed without merging